version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ngim-postgres
    environment:
      POSTGRES_DB: next_gen_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
